[package]
name = "pipewire"
version = "1.6.8"

[package.upstream]
url = "https://gitlab.freedesktop.org/pipewire/pipewire.git"
commit = "b741e0c74f5436f0c925f7741140db0efd32cf4e"

[publish]
copy = [
  { from = "source/spa/include/spa/buffer/*.h", to = "include/spa/buffer" },
  { from = "source/spa/include/spa/control/*.h", to = "include/spa/control" },
  { from = "source/spa/include/spa/debug/*.h", to = "include/spa/debug" },
  { from = "source/spa/include/spa/filter-graph/*.h", to = "include/spa/filter-graph" },
  { from = "source/spa/include/spa/graph/*.h", to = "include/spa/graph" },
  { from = "source/spa/include/spa/interfaces/audio/*.h", to = "include/spa/interfaces/audio" },
  { from = "source/spa/include/spa/monitor/*.h", to = "include/spa/monitor" },
  { from = "source/spa/include/spa/node/*.h", to = "include/spa/node" },
  { from = "source/spa/include/spa/param/*.h", to = "include/spa/param" },
  { from = "source/spa/include/spa/param/audio/*.h", to = "include/spa/param/audio" },
  { from = "source/spa/include/spa/param/bluetooth/*.h", to = "include/spa/param/bluetooth" },
  { from = "source/spa/include/spa/param/video/*.h", to = "include/spa/param/video" },
  { from = "source/spa/include/spa/pod/*.h", to = "include/spa/pod" },
  { from = "source/spa/include/spa/support/*.h", to = "include/spa/support" },
  { from = "source/spa/include/spa/utils/*.h", to = "include/spa/utils" },
  { from = "source/src/pipewire/array.h", to = "include/pipewire/array.h" },
  { from = "source/src/pipewire/buffers.h", to = "include/pipewire/buffers.h" },
  { from = "source/src/pipewire/capabilities.h", to = "include/pipewire/capabilities.h" },
  { from = "source/src/pipewire/client.h", to = "include/pipewire/client.h" },
  { from = "source/src/pipewire/conf.h", to = "include/pipewire/conf.h" },
  { from = "source/src/pipewire/context.h", to = "include/pipewire/context.h" },
  { from = "source/src/pipewire/control.h", to = "include/pipewire/control.h" },
  { from = "source/src/pipewire/core.h", to = "include/pipewire/core.h" },
  { from = "source/src/pipewire/data-loop.h", to = "include/pipewire/data-loop.h" },
  { from = "source/src/pipewire/device.h", to = "include/pipewire/device.h" },
  { from = "source/src/pipewire/factory.h", to = "include/pipewire/factory.h" },
  { from = "source/src/pipewire/filter.h", to = "include/pipewire/filter.h" },
  { from = "source/src/pipewire/global.h", to = "include/pipewire/global.h" },
  { from = "source/src/pipewire/i18n.h", to = "include/pipewire/i18n.h" },
  { from = "source/src/pipewire/impl.h", to = "include/pipewire/impl.h" },
  { from = "source/src/pipewire/impl-client.h", to = "include/pipewire/impl-client.h" },
  { from = "source/src/pipewire/impl-core.h", to = "include/pipewire/impl-core.h" },
  { from = "source/src/pipewire/impl-device.h", to = "include/pipewire/impl-device.h" },
  { from = "source/src/pipewire/impl-factory.h", to = "include/pipewire/impl-factory.h" },
  { from = "source/src/pipewire/impl-link.h", to = "include/pipewire/impl-link.h" },
  { from = "source/src/pipewire/impl-metadata.h", to = "include/pipewire/impl-metadata.h" },
  { from = "source/src/pipewire/impl-module.h", to = "include/pipewire/impl-module.h" },
  { from = "source/src/pipewire/impl-node.h", to = "include/pipewire/impl-node.h" },
  { from = "source/src/pipewire/impl-port.h", to = "include/pipewire/impl-port.h" },
  { from = "source/src/pipewire/keys.h", to = "include/pipewire/keys.h" },
  { from = "source/src/pipewire/link.h", to = "include/pipewire/link.h" },
  { from = "source/src/pipewire/log.h", to = "include/pipewire/log.h" },
  { from = "source/src/pipewire/loop.h", to = "include/pipewire/loop.h" },
  { from = "source/src/pipewire/main-loop.h", to = "include/pipewire/main-loop.h" },
  { from = "source/src/pipewire/map.h", to = "include/pipewire/map.h" },
  { from = "source/src/pipewire/mem.h", to = "include/pipewire/mem.h" },
  { from = "source/src/pipewire/module.h", to = "include/pipewire/module.h" },
  { from = "source/src/pipewire/node.h", to = "include/pipewire/node.h" },
  { from = "source/src/pipewire/permission.h", to = "include/pipewire/permission.h" },
  { from = "source/src/pipewire/pipewire.h", to = "include/pipewire/pipewire.h" },
  { from = "source/src/pipewire/port.h", to = "include/pipewire/port.h" },
  { from = "source/src/pipewire/properties.h", to = "include/pipewire/properties.h" },
  { from = "source/src/pipewire/protocol.h", to = "include/pipewire/protocol.h" },
  { from = "source/src/pipewire/proxy.h", to = "include/pipewire/proxy.h" },
  { from = "source/src/pipewire/resource.h", to = "include/pipewire/resource.h" },
  { from = "source/src/pipewire/stream.h", to = "include/pipewire/stream.h" },
  { from = "source/src/pipewire/thread.h", to = "include/pipewire/thread.h" },
  { from = "source/src/pipewire/thread-loop.h", to = "include/pipewire/thread-loop.h" },
  { from = "source/src/pipewire/timer-queue.h", to = "include/pipewire/timer-queue.h" },
  { from = "source/src/pipewire/type.h", to = "include/pipewire/type.h" },
  { from = "source/src/pipewire/utils.h", to = "include/pipewire/utils.h" },
  { from = "source/src/pipewire/work-queue.h", to = "include/pipewire/work-queue.h" },
  { from = "source/src/pipewire/extensions/*.h", to = "include/pipewire/extensions" },
  { from = "source/src/pipewire/extensions/session-manager/*.h", to = "include/pipewire/extensions/session-manager" },
  { from = "manifest/gen/pipewire/version.h", to = "include/pipewire/version.h" },
]
