[package]
name = "toolchains"
version = "0.1.0"
author = "tspader"
maintainer = "tspader"

[[toolchain]]
name = "gcc"
compiler = "gcc"
linker = "ld"
archiver = "ar"
driver = "gcc"
abi = "gnu"
export = true

[[toolchain]]
name = "tcc"
compiler = "tcc"
linker = "ld"
archiver = "ar"
driver = "gcc"
abi = "gnu"
export = true

[[toolchain]]
name = "clang"
compiler = "clang"
linker = "ld"
archiver = "ar"
driver = "gcc"
abi = "gnu"
export = true

[[toolchain]]
name = "x86_64-linux-musl-native"
url = "https://musl.cc/x86_64-linux-musl-native.tgz"
compiler = "bin/x86_64-linux-musl-gcc"
linker = "x86_64-linux-musl/bin/ld"
archiver = "x86_64-linux-musl/bin/ar"
driver = "gcc"
export = true
