[package]
name = "toml"
url = "https://github.com/tspader/toml.git"
version = "1.5.1"
commit = "2e8ffdfa215c"
author = "cktan"
maintainer = "tspader"

[options.strict]
type = "bool"
default = false

[[lib]]
name = "toml"
kinds = ["source"]

[publish]
copy = [
  { from = "source/toml.h", to = "include" },
]
