#include "spn.h"

static const c8* SDL_CONFIG =
  "#ifndef SDL_config_h_\n"
  "#define SDL_config_h_\n"
  "#include \"SDL_platform.h\"\n"
  "#if defined(__WIN32__)\n"
  "#include \"SDL_config_windows.h\"\n"
  "#undef HAVE_WINDOWS_GAMING_INPUT_H\n"
  "#undef SDL_JOYSTICK_WGI\n"
  "#elif defined(__MACOSX__)\n"
  "#include \"SDL_config_macosx.h\"\n"
  "#elif defined(__LINUX__)\n"
  "#include \"SDL_config_spn.h\"\n"
  "#else\n"
  "#error spn sdl2: unsupported platform\n"
  "#endif\n"
  "#endif\n";

static const c8* SDL_REVISION =
  "#define SDL_REVISION \"SDL-2.30.4 (spn)\"\n"
  "#define SDL_REVISION_NUMBER 0\n";

static const c8* SDL_CONFIG_SPN =
  "#ifndef SDL_config_spn_h_\n"
  "#define SDL_config_spn_h_\n"
  "\n"
  "#ifndef _LARGEFILE64_SOURCE\n"
  "#define _LARGEFILE64_SOURCE 1\n"
  "#endif\n"
  "\n"
  "#if defined(__LP64__) || defined(_LP64)\n"
  "#define SIZEOF_VOIDP 8\n"
  "#else\n"
  "#define SIZEOF_VOIDP 4\n"
  "#endif\n"
  "\n"
  "#define HAVE_GCC_ATOMICS 1\n"
  "\n"
  "#define HAVE_LIBC 1\n"
  "#define STDC_HEADERS 1\n"
  "#define HAVE_ALLOCA_H 1\n"
  "#define HAVE_CTYPE_H 1\n"
  "#define HAVE_FLOAT_H 1\n"
  "#define HAVE_ICONV_H 1\n"
  "#define HAVE_INTTYPES_H 1\n"
  "#define HAVE_LIMITS_H 1\n"
  "#define HAVE_MALLOC_H 1\n"
  "#define HAVE_MATH_H 1\n"
  "#define HAVE_MEMORY_H 1\n"
  "#define HAVE_SIGNAL_H 1\n"
  "#define HAVE_STDARG_H 1\n"
  "#define HAVE_STDDEF_H 1\n"
  "#define HAVE_STDINT_H 1\n"
  "#define HAVE_STDIO_H 1\n"
  "#define HAVE_STDLIB_H 1\n"
  "#define HAVE_STRINGS_H 1\n"
  "#define HAVE_STRING_H 1\n"
  "#define HAVE_SYS_TYPES_H 1\n"
  "#define HAVE_WCHAR_H 1\n"
  "#define HAVE_LINUX_INPUT_H 1\n"
  "\n"
  "#define HAVE_DLOPEN 1\n"
  "#define HAVE_MALLOC 1\n"
  "#define HAVE_CALLOC 1\n"
  "#define HAVE_REALLOC 1\n"
  "#define HAVE_FREE 1\n"
  "#define HAVE_ALLOCA 1\n"
  "#define HAVE_GETENV 1\n"
  "#define HAVE_SETENV 1\n"
  "#define HAVE_PUTENV 1\n"
  "#define HAVE_UNSETENV 1\n"
  "#define HAVE_QSORT 1\n"
  "#define HAVE_BSEARCH 1\n"
  "#define HAVE_ABS 1\n"
  "#define HAVE_BCOPY 1\n"
  "#define HAVE_MEMSET 1\n"
  "#define HAVE_MEMCPY 1\n"
  "#define HAVE_MEMMOVE 1\n"
  "#define HAVE_MEMCMP 1\n"
  "#define HAVE_WCSLEN 1\n"
  "#define HAVE_WCSDUP 1\n"
  "#define HAVE_WCSSTR 1\n"
  "#define HAVE_WCSCMP 1\n"
  "#define HAVE_WCSNCMP 1\n"
  "#define HAVE_WCSCASECMP 1\n"
  "#define HAVE_WCSNCASECMP 1\n"
  "#define HAVE_STRLEN 1\n"
  "#define HAVE_INDEX 1\n"
  "#define HAVE_RINDEX 1\n"
  "#define HAVE_STRCHR 1\n"
  "#define HAVE_STRRCHR 1\n"
  "#define HAVE_STRSTR 1\n"
  "#define HAVE_STRTOK_R 1\n"
  "#define HAVE_STRTOL 1\n"
  "#define HAVE_STRTOUL 1\n"
  "#define HAVE_STRTOLL 1\n"
  "#define HAVE_STRTOULL 1\n"
  "#define HAVE_STRTOD 1\n"
  "#define HAVE_ATOI 1\n"
  "#define HAVE_ATOF 1\n"
  "#define HAVE_STRCMP 1\n"
  "#define HAVE_STRNCMP 1\n"
  "#define HAVE_STRCASECMP 1\n"
  "#define HAVE_STRNCASECMP 1\n"
  "#define HAVE_STRCASESTR 1\n"
  "#define HAVE_SSCANF 1\n"
  "#define HAVE_VSSCANF 1\n"
  "#define HAVE_VSNPRINTF 1\n"
  "#define HAVE_M_PI 1\n"
  "#define HAVE_ACOS 1\n"
  "#define HAVE_ACOSF 1\n"
  "#define HAVE_ASIN 1\n"
  "#define HAVE_ASINF 1\n"
  "#define HAVE_ATAN 1\n"
  "#define HAVE_ATANF 1\n"
  "#define HAVE_ATAN2 1\n"
  "#define HAVE_ATAN2F 1\n"
  "#define HAVE_CEIL 1\n"
  "#define HAVE_CEILF 1\n"
  "#define HAVE_COPYSIGN 1\n"
  "#define HAVE_COPYSIGNF 1\n"
  "#define HAVE_COS 1\n"
  "#define HAVE_COSF 1\n"
  "#define HAVE_EXP 1\n"
  "#define HAVE_EXPF 1\n"
  "#define HAVE_FABS 1\n"
  "#define HAVE_FABSF 1\n"
  "#define HAVE_FLOOR 1\n"
  "#define HAVE_FLOORF 1\n"
  "#define HAVE_FMOD 1\n"
  "#define HAVE_FMODF 1\n"
  "#define HAVE_LOG 1\n"
  "#define HAVE_LOGF 1\n"
  "#define HAVE_LOG10 1\n"
  "#define HAVE_LOG10F 1\n"
  "#define HAVE_LROUND 1\n"
  "#define HAVE_LROUNDF 1\n"
  "#define HAVE_POW 1\n"
  "#define HAVE_POWF 1\n"
  "#define HAVE_ROUND 1\n"
  "#define HAVE_ROUNDF 1\n"
  "#define HAVE_SCALBN 1\n"
  "#define HAVE_SCALBNF 1\n"
  "#define HAVE_SIN 1\n"
  "#define HAVE_SINF 1\n"
  "#define HAVE_SQRT 1\n"
  "#define HAVE_SQRTF 1\n"
  "#define HAVE_TAN 1\n"
  "#define HAVE_TANF 1\n"
  "#define HAVE_TRUNC 1\n"
  "#define HAVE_TRUNCF 1\n"
  "#define HAVE_FOPEN64 1\n"
  "#define HAVE_FSEEKO 1\n"
  "#define HAVE_FSEEKO64 1\n"
  "#define HAVE_MEMFD_CREATE 1\n"
  "#define HAVE_POSIX_FALLOCATE 1\n"
  "#define HAVE_SIGACTION 1\n"
  "#define HAVE_SA_SIGACTION 1\n"
  "#define HAVE_SETJMP 1\n"
  "#define HAVE_NANOSLEEP 1\n"
  "#define HAVE_SYSCONF 1\n"
  "#define HAVE_CLOCK_GETTIME 1\n"
  "#define HAVE_GETPAGESIZE 1\n"
  "#define HAVE_MPROTECT 1\n"
  "#define HAVE_ICONV 1\n"
  "#define HAVE_PTHREAD_SETNAME_NP 1\n"
  "#define HAVE_SEM_TIMEDWAIT 1\n"
  "#define HAVE_GETAUXVAL 1\n"
  "#define HAVE_POLL 1\n"
  "#define HAVE__EXIT 1\n"
  "\n"
  "#define HAVE_SYS_INOTIFY_H 1\n"
  "#define HAVE_INOTIFY_INIT 1\n"
  "#define HAVE_INOTIFY_INIT1 1\n"
  "#define HAVE_INOTIFY 1\n"
  "#define HAVE_O_CLOEXEC 1\n"
  "\n"
  "#if defined(__i386__) || defined(__x86_64__)\n"
  "#define HAVE_IMMINTRIN_H 1\n"
  "#endif\n"
  "\n"
  "#define SDL_AUDIO_DRIVER_DISK 1\n"
  "#define SDL_AUDIO_DRIVER_DUMMY 1\n"
  "#ifdef SPN_SDL_ALSA\n"
  "#define SDL_AUDIO_DRIVER_ALSA 1\n"
  "#define SDL_AUDIO_DRIVER_ALSA_DYNAMIC \"libasound.so.2\"\n"
  "#endif\n"
  "#ifdef SPN_SDL_PULSEAUDIO\n"
  "#define SDL_AUDIO_DRIVER_PULSEAUDIO 1\n"
  "#define SDL_AUDIO_DRIVER_PULSEAUDIO_DYNAMIC \"libpulse.so.0\"\n"
  "#endif\n"
  "#ifdef SPN_SDL_PIPEWIRE\n"
  "#define SDL_AUDIO_DRIVER_PIPEWIRE 1\n"
  "#define SDL_AUDIO_DRIVER_PIPEWIRE_DYNAMIC \"libpipewire-0.3.so.0\"\n"
  "#endif\n"
  "#ifdef SPN_SDL_OSS\n"
  "#define SDL_AUDIO_DRIVER_OSS 1\n"
  "#endif\n"
  "\n"
  "#define SDL_INPUT_LINUXEV 1\n"
  "#define SDL_INPUT_LINUXKD 1\n"
  "#define SDL_JOYSTICK_LINUX 1\n"
  "#define SDL_JOYSTICK_VIRTUAL 1\n"
  "#define SDL_HAPTIC_LINUX 1\n"
  "#ifdef SPN_SDL_UDEV\n"
  "#define HAVE_LIBUDEV_H 1\n"
  "#define SDL_UDEV_DYNAMIC \"libudev.so.1\"\n"
  "#define SDL_JOYSTICK_HIDAPI 1\n"
  "#endif\n"
  "\n"
  "#define SDL_SENSOR_DUMMY 1\n"
  "#define SDL_LOADSO_DLOPEN 1\n"
  "#define SDL_THREAD_PTHREAD 1\n"
  "#define SDL_THREAD_PTHREAD_RECURSIVE_MUTEX 1\n"
  "#define SDL_TIMER_UNIX 1\n"
  "#define SDL_FILESYSTEM_UNIX 1\n"
  "#define SDL_POWER_LINUX 1\n"
  "\n"
  "#define SDL_VIDEO_DRIVER_DUMMY 1\n"
  "#define SDL_VIDEO_DRIVER_OFFSCREEN 1\n"
  "#ifdef SPN_SDL_X11\n"
  "#define SDL_VIDEO_DRIVER_X11 1\n"
  "#define SDL_VIDEO_DRIVER_X11_DYNAMIC \"libX11.so.6\"\n"
  "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT \"libXext.so.6\"\n"
  "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR \"libXcursor.so.1\"\n"
  "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2 \"libXi.so.6\"\n"
  "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XFIXES \"libXfixes.so.3\"\n"
  "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR \"libXrandr.so.2\"\n"
  "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XSS \"libXss.so.1\"\n"
  "#define SDL_VIDEO_DRIVER_X11_XCURSOR 1\n"
  "#define SDL_VIDEO_DRIVER_X11_XDBE 1\n"
  "#define SDL_VIDEO_DRIVER_X11_XINPUT2 1\n"
  "#define SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH 1\n"
  "#define SDL_VIDEO_DRIVER_X11_XFIXES 1\n"
  "#define SDL_VIDEO_DRIVER_X11_XRANDR 1\n"
  "#define SDL_VIDEO_DRIVER_X11_XSCRNSAVER 1\n"
  "#define SDL_VIDEO_DRIVER_X11_XSHAPE 1\n"
  "#define SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS 1\n"
  "#define SDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM 1\n"
  "#define SDL_VIDEO_OPENGL_GLX 1\n"
  "#endif\n"
  "\n"
  "#define SDL_VIDEO_OPENGL 1\n"
  "#define SDL_VIDEO_OPENGL_EGL 1\n"
  "#define SDL_VIDEO_OPENGL_ES2 1\n"
  "#define SDL_VIDEO_RENDER_OGL 1\n"
  "#define SDL_VIDEO_RENDER_OGL_ES2 1\n"
  "#define SDL_VIDEO_VULKAN 1\n"
  "\n"
  "#ifdef SPN_SDL_DBUS\n"
  "#define HAVE_DBUS_DBUS_H 1\n"
  "#define HAVE_FCITX 1\n"
  "#define SDL_USE_IME 1\n"
  "#endif\n"
  "\n"
  "#define DYNAPI_NEEDS_DLOPEN 1\n"
  "\n"
  "#endif\n";

SPN_EXPORT
s32 stage_headers(spn_t* spn, spn_node_ctx_t* ctx) {
  if (spn_copy(spn, SPN_DIR_SOURCE, "include/*.h", SPN_DIR_WORK, "SDL2")) {
    return 1;
  }
  spn_write_file(spn, "SDL2/SDL_config.h", SDL_CONFIG);
  spn_write_file(spn, "SDL2/SDL_config_spn.h", SDL_CONFIG_SPN);
  spn_write_file(spn, "SDL2/SDL_revision.h", SDL_REVISION);
  return 0;
}

SPN_EXPORT
s32 package(spn_t* spn, spn_node_ctx_t* ctx) {
  return spn_copy(spn, SPN_DIR_WORK, "SDL2/*", SPN_DIR_INCLUDE, "");
}

SPN_EXPORT
spn_err_t configure(spn_t* spn, spn_config_t* config) {
  const c8* staged = spn_get_subdir(spn, SPN_DIR_WORK, "SDL2");

  spn_target_t* sdl = spn_get_target(spn, "SDL2");
  spn_target_add_include(sdl, staged);
  spn_target_add_include(sdl, spn_get_subdir(spn, SPN_DIR_SOURCE, "src/video/khronos"));

  spn_target_t* sdl_main = spn_get_target(spn, "SDL2main");
  spn_target_add_include(sdl_main, staged);

  spn_node_t* headers = spn_add_node(config, "headers");
  spn_node_set_fn(headers, "stage_headers");
  spn_node_add_output(headers, spn_get_subdir(spn, SPN_DIR_WORK, "SDL2/SDL_config.h"));

  return SPN_OK;
}
