[package]
name = "tracy"
version = "0.11.1"
system_deps = [
  { lib = "pthread", when = { os = "linux" } },
  { lib = "dl", when = { os = "linux" } },
]

[package.upstream]
url = "https://github.com/wolfpld/tracy.git"
commit = "5d542dc09f3d9378d005092a4ad446bd405f819a"

[options.enable]
type = "bool"
default = false
define = "TRACY_ENABLE"
public = true

[[lib]]
name = "tracy"
kinds = ["static"]
source = ["public/TracyClient.cpp"]
include = ["public"]
cxx = { standard = "c++11" }

[[example]]
name = "workload"
source = [{ path = "example/workload.cpp", tree = "manifest" }]
deps = ["tracy"]
cxx = { standard = "c++17" }

[profile.default]
options = { enable = true }

[publish]
copy = [
  { from = "source/public/tracy/*", to = "include/tracy" },
  { from = "source/public/common/*", to = "include/common" },
  { from = "source/public/client/*", to = "include/client" },
]
