[package]
name = "libxinerama"
version = "1.1.6"

[package.upstream]
url = "https://gitlab.freedesktop.org/xorg/lib/libxinerama.git"
commit = "cc4ac9cf36fdf3815381b791e47a90b8aebc7e78"

[publish]
copy = [
  { from = "source/include/X11/extensions/*.h", to = "include/X11/extensions" },
]
