[package]
name = "imgui"
version = "1.90.8"

[package.upstream]
url = "https://github.com/ocornut/imgui.git"
commit = "2ae16655a7072546bb23a3dfc8e1735cf0185b29"

[options.sdl2]
type = "bool"
default = false

[options.opengl3]
type = "bool"
default = false

[deps.package]
sdl2 = { version = "^2.30.0", when = { sdl2 = true } }

[[lib]]
name = "imgui"
kinds = ["static", "shared"]
source = [
  "imgui.cpp",
  "imgui_demo.cpp",
  "imgui_draw.cpp",
  "imgui_tables.cpp",
  "imgui_widgets.cpp",
  { path = "backends/imgui_impl_sdl2.cpp", when = { sdl2 = true } },
  { path = "backends/imgui_impl_opengl3.cpp", when = { opengl3 = true } },
]
include = ["."]
flags = [
  { value = "-idirafter", when = { sdl2 = true, os = "linux" } },
  { value = "/usr/include", when = { sdl2 = true, os = "linux" } },
]
system_deps = [
  { value = "dl", when = { opengl3 = true, os = "linux" } },
]
cxx = { standard = "c++17" }

[[example]]
name = "headless"
source = [{ path = "example/headless.cpp", tree = "manifest" }]
deps = ["imgui"]
cxx = { standard = "c++17" }

[[example]]
name = "window"
source = [{ path = "example/window.cpp", tree = "manifest" }]
deps = ["imgui"]
cxx = { standard = "c++17" }

[[toolchain]]
name = "native"
compiler = "clang"
linker = "clang"
archiver = "ar"
driver = "clang"
cxx = "clang++"

[profile.default]
toolchain = "native"
linkage = "shared"
abi = "gnu"
options = { sdl2 = true, opengl3 = true }

[config.sdl2]
options = { x11 = true }

[publish]
copy = [
  { from = "source/*.h", to = "include/imgui" },
  { from = "source/backends/*.h", to = "include/imgui" },
]
