[package]
namespace = "spader"
name = "sp"
url = "https://github.com/tspader/sp.git"
version = "3.0.0"
commit = "ede42f835f63cdaf1d90c5eeeb9eaa1205ada954"
author = "tspader"
maintainer = "tspader"
system_deps = ["m"]

[[lib]]
name = "sp"
kinds = ["source"]
