[package]
namespace = "spader"
name = "sp"
url = "https://github.com/tspader/sp.git"
version = "2.0.0"
commit = "88025c90637f0d412e5150c4885b2c9f4c354bbb"
author = "tspader"
maintainer = "tspader"
system_deps = ["m"]

[[lib]]
name = "sp"
kinds = ["source"]
