#include "spn.h"

// TCC unconditionally includes config.h, so a file has to exist, but
// spn natively understands preprocessor definitions so we configure
// it that way and leave the file empty
SPN_EXPORT
s32 gen_config(spn_t* spn, spn_node_ctx_t* ctx) {
  spn_io_write("/work/config.h", "/* generated by spn; configuration is passed as defines */\n");
  return 0;
}

SPN_EXPORT
spn_err_t configure(spn_t* spn, spn_config_t* config) {
  spn_node_t* gen = spn_add_node(config, "config.h");
  spn_node_set_fn(gen, "gen_config");
  spn_node_add_output(gen, spn_get_subdir(spn, SPN_DIR_WORK, "config.h"));

  // Set everyone up to have config.h on their include path
  const c8* targets [] = { "tcc", "tcc1", "runtime", "bcheck" };
  for (u32 it = 0; it < 4; it++) {
    spn_target_add_include(spn_get_target(spn, targets[it]), spn_get_dir(spn, SPN_DIR_WORK));
  }

  spn_target_t* tcc = spn_get_target(spn, "tcc");
  spn_target_add_define(tcc, spn_fmt("CONFIG_TCCDIR=\"{}\"", spn_get_subdir(spn, SPN_DIR_LIB, "tcc")));

  spn_target_t* bcheck = spn_get_target(spn, "bcheck");
  switch (spn_profile_get_libc(spn_get_profile(spn))) {
    case SPN_LIBC_MUSL: {
      spn_target_add_define(tcc, "CONFIG_TCC_MUSL=1");
      spn_target_add_define(tcc, "CONFIG_TCC_ELFINTERP=\"/lib/ld-musl-x86_64.so.1\"");
      // bcheck branches on musl for its allocator hooks
      spn_target_add_define(bcheck, "CONFIG_TCC_MUSL=1");
      break;
    }
    default: {
      spn_target_add_define(tcc, "CONFIG_LDDIR=\"lib64\"");
      break;
    }
  }

  return SPN_OK;
}
