#include "spn.h"

// TCC unconditionally includes config.h, so a file has to exist, but
// spn natively understands preprocessor definitions so we configure
// it that way and leave the file empty
s32 gen_config(spn_t* spn, spn_node_ctx_t* ctx) {
  spn_write_file(spn, "config.h", "/* generated by spn; configuration is passed as defines */\n");
  return 0;
}

// CONFIG_TCCDIR="<store>/lib/tcc"; the only define whose value isn't a literal
static const c8* define_tccdir(spn_t* spn) {
  static c8 buf [512];
  const c8* prefix = "CONFIG_TCCDIR=\"";
  const c8* path = spn_get_subdir(spn, SPN_DIR_LIB, "tcc");

  u32 len = 0;
  for (const c8* c = prefix; *c; c++) buf[len++] = *c;
  for (const c8* c = path; *c && len + 2 < sizeof(buf); c++) buf[len++] = *c;
  buf[len++] = '"';
  buf[len] = 0;
  return buf;
}

spn_err_t configure(spn_t* spn, spn_config_t* config) {
  spn_node_t* gen = spn_add_node(config, "config.h");
  spn_node_set_fn(gen, gen_config);
  spn_node_add_output(gen, spn_get_subdir(spn, SPN_DIR_WORK, "config.h"));

  // Set everyone up to have config.h on their include path
  const c8* targets [] = { "tcc", "tcc1", "runtime", "bcheck" };
  for (u32 it = 0; it < 4; it++) {
    spn_target_add_include(spn_get_target(spn, targets[it]), spn_get_dir(spn, SPN_DIR_WORK));
  }

  spn_target_t* tcc = spn_get_target(spn, "tcc");
  spn_target_add_define(tcc, define_tccdir(spn));

  spn_target_t* bcheck = spn_get_target(spn, "bcheck");
  switch (spn_profile_get_libc(spn_get_profile(spn))) {
    case SPN_LIBC_MUSL: {
      spn_target_add_define(tcc, "CONFIG_TCC_MUSL=1");
      spn_target_add_define(tcc, "CONFIG_TCC_ELFINTERP=\"/lib/ld-musl-x86_64.so.1\"");
      // bcheck branches on musl for its allocator hooks
      spn_target_add_define(bcheck, "CONFIG_TCC_MUSL=1");
      break;
    }
    default: {
      spn_target_add_define(tcc, "CONFIG_LDDIR=\"lib64\"");
      break;
    }
  }

  return SPN_OK;
}

spn_err_t package(spn_t* spn) {
  if (spn_copy(spn, SPN_DIR_LIB, "libtcc1.a", SPN_DIR_LIB, "tcc/libtcc1.a")) return SPN_ERROR;
  if (spn_copy(spn, SPN_DIR_LIB, "lib/*.o", SPN_DIR_LIB, "tcc")) return SPN_ERROR;
  if (spn_copy(spn, SPN_DIR_SOURCE, "include/*", SPN_DIR_LIB, "tcc/include")) return SPN_ERROR;
  if (spn_copy(spn, SPN_DIR_SOURCE, "tcclib.h", SPN_DIR_LIB, "tcc/include/tcclib.h")) return SPN_ERROR;
  return SPN_OK;
}
