[package]
name = "libxrender"
version = "0.9.12"

[package.upstream]
url = "https://gitlab.freedesktop.org/xorg/lib/libxrender.git"
commit = "46e12ff9e8e4d3f0313a2f097df93dbfdc14f92f"

[publish]
copy = [
  { from = "source/include/X11/extensions/*.h", to = "include/X11/extensions" },
]
